### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-sonnenstrahl#1]
# Backend
- [x] Tarife (plans)
  - [x] CSV Import
  - [x] List
  - [x] Create
  - [x] Read
  - [x] Update
  - [x] Delete

- [x] Bestellungen (orders)
  - [x] List
  - [x] Create
  - [x] Read
  - [x] Update @DominikRuf 
  - [x] Delete
  - [x] Permission check
    - [x] Jeder darf Bestellungen anlegen
    - [x] Admins dürfen bearbeiten und löschen
    - [x] Besteller darf bearbeiten und löschen
  - [x] Kündigung 
  - [x] Vertragslaufzeit
  - [x] Export aller Bestellungen (als Admin)

- [x] Kunden (customers)
  - [x] List
  - [x] Create
  - [x] Read
  - [x] Update
  - [x] Delete
  - [x] Permission check
    - [x] Jeder darf Customer anlegen
    - [x] Admins dürfen bearbeiten und löschen
    - [x] User darf sich selbst bearbeiten und löschen

- [x] Benutzer
  - [x] Create @LisaFremdt
  - [x] Read
  - [x] Update
  - [x] Delete
  - [x] Verschiedene Permission Level (Is_Admin true/false)
  - [x] Permission check
    - [x] Jeder darf User anlegen
    - [x] Admins dürfen bearbeiten und löschen
    - [x] User darf sich selbst bearbeiten und löschen
  - [x] Login / Logout mit JWT

- [x] Errorhandling mit korrekten HTTP Statuscodes @TomasKostadinov 

- [x] Querybuilder sort by Bug fixen @TomasKostadinov

- [x] Database Seeder

# Frontend
- [x] Grafischer Bestellprozess
- [x] Grafischer Rechner
- [x] Profil bearbeiten / Löschen
- [x] Login/Logout/Registrierung

- [x] Admin Panel
  - [x] Umsatzanzeige mit Graphen
  - [x] Export aller Bestellungen
  - [x] Daten
